method_name: abc
seed: 11111
data_dir: /mnt/d/workspace/personal/master_lectures/521158S_nlp/project/nlp_1st_sem/Data
checkpoint_dir: /mnt/d/workspace/personal/master_lectures/521158S_nlp/project/weights
num_classes: 5

use_lexicon: False
embedding_model: roberta
fc_only: True
use_pooler: True
use_transformer: False

dropout: 0.0
max_length: 512
weight_decay: 1e-4
loss_weight: 0.5
class_balance: 2.0
batch_size: 32
num_workers: 8
num_epochs: 1
learning_rate: 0.0
milestones: [50]
gamma: 0.1

print_step: 60
save_step: 10
